-- Baseball Analytics Platform on OCI
-- Part 1 Autonomous Database bootstrap
--
-- Run as ADMIN after Terraform provisions ADB.
-- Replace every placeholder password before execution.
-- Store production passwords in an approved secret-management workflow.

SET DEFINE OFF;

--------------------------------------------------------------------------------
-- Canonical schema families
--------------------------------------------------------------------------------

CREATE USER STG IDENTIFIED BY "<STG_password>"
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA;

CREATE USER CUR IDENTIFIED BY "<CUR_password>"
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA;

CREATE USER FEAT IDENTIFIED BY "<FEAT_password>"
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA;

CREATE USER ML IDENTIFIED BY "<ML_password>"
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO STG;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO CUR;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO FEAT;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO ML;

--------------------------------------------------------------------------------
-- Required ingestion lineage and data-quality objects
--------------------------------------------------------------------------------

CREATE TABLE STG.INGEST_RUNS (
  ingest_run_id    VARCHAR2(64 CHAR)                    NOT NULL,
  source           VARCHAR2(128 CHAR)                   NOT NULL,
  start_ts         TIMESTAMP WITH TIME ZONE             NOT NULL,
  end_ts           TIMESTAMP WITH TIME ZONE,
  status           VARCHAR2(32 CHAR)                    NOT NULL,
  records_landed   NUMBER,
  records_loaded   NUMBER,
  notes            CLOB,
  created_ts       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_ingest_runs PRIMARY KEY (ingest_run_id),
  CONSTRAINT ck_ingest_runs_status
    CHECK (status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'PARTIAL', 'CANCELLED')),
  CONSTRAINT ck_ingest_runs_counts
    CHECK (
      (records_landed IS NULL OR records_landed >= 0)
      AND (records_loaded IS NULL OR records_loaded >= 0)
    )
);

CREATE TABLE STG.FILE_MANIFEST (
  manifest_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
  ingest_run_id        VARCHAR2(64 CHAR)                              NOT NULL,
  source               VARCHAR2(128 CHAR)                             NOT NULL,
  object_storage_path  VARCHAR2(1024 CHAR)                            NOT NULL,
  etag_or_checksum     VARCHAR2(256 CHAR),
  row_count            NUMBER,
  load_status          VARCHAR2(32 CHAR) DEFAULT 'LANDED'             NOT NULL,
  loaded_ts            TIMESTAMP WITH TIME ZONE,
  created_ts           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_file_manifest PRIMARY KEY (manifest_id),
  CONSTRAINT uq_file_manifest_path UNIQUE (object_storage_path),
  CONSTRAINT fk_file_manifest_ingest_run
    FOREIGN KEY (ingest_run_id) REFERENCES STG.INGEST_RUNS (ingest_run_id),
  CONSTRAINT ck_file_manifest_row_count
    CHECK (row_count IS NULL OR row_count >= 0),
  CONSTRAINT ck_file_manifest_status
    CHECK (load_status IN ('LANDED', 'LOADING', 'LOADED', 'FAILED', 'SKIPPED'))
);

CREATE INDEX STG.IX_FILE_MANIFEST_RUN
  ON STG.FILE_MANIFEST (ingest_run_id);

CREATE TABLE STG.DQ_RESULTS (
  dq_result_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
  ingest_run_id   VARCHAR2(64 CHAR)                              NOT NULL,
  check_name      VARCHAR2(256 CHAR)                             NOT NULL,
  check_level     VARCHAR2(16 CHAR)                              NOT NULL,
  pass_flag       CHAR(1 CHAR)                                  NOT NULL,
  details         CLOB,
  checked_ts      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_dq_results PRIMARY KEY (dq_result_id),
  CONSTRAINT fk_dq_results_ingest_run
    FOREIGN KEY (ingest_run_id) REFERENCES STG.INGEST_RUNS (ingest_run_id),
  CONSTRAINT ck_dq_results_level
    CHECK (check_level IN ('INFO', 'WARN', 'FAIL')),
  CONSTRAINT ck_dq_results_pass
    CHECK (pass_flag IN ('Y', 'N'))
);

CREATE INDEX STG.IX_DQ_RESULTS_RUN
  ON STG.DQ_RESULTS (ingest_run_id);

--------------------------------------------------------------------------------
-- Verification
--------------------------------------------------------------------------------

SELECT username
FROM all_users
WHERE username IN ('STG', 'CUR', 'FEAT', 'ML')
ORDER BY username;

SELECT owner, table_name
FROM all_tables
WHERE owner = 'STG'
  AND table_name IN ('INGEST_RUNS', 'FILE_MANIFEST', 'DQ_RESULTS')
ORDER BY table_name;

PROMPT Part 1 ADB bootstrap completed.
